### ISSUE TITLE
Quoted image within "%20" inside the image link become broken image

### ISSUE THREAD

**Issue by coolkips** [idoenk/kaskus-quick-reply#3]
Example: Try to quote this post: http://www.kaskus.co.id/show_post/560fc74d56e6afa57a8b456a/1862/

Original image link:
http://i1276.photobucket.com/albums/y471/Aindonesia14/2015-10-03%2018_46_56-GAME%20-%20Clover_zpspgb6cb6k.png

After quoted, the image link become:
http://i1276.photobucket.com/albums/y471/Aindonesia14/2015-10-03%252018_46_56-GAME%2520-%2520Clover_zpspgb6cb6k.png

So, i found %20 replaced by %2520 (unwanted '25' insertion after quote)

Proof: After quoted ---> http://www.kaskus.co.id/show_post/560fdcb79a095147088b456c/1863/

**Comment by s4nji** [comment]
Removing `encodeURI()` on line [5343](https://github.com/idoenk/kaskus-quick-reply/blob/master/kaskus_quick_reply.user.js#L5343) and [5347](https://github.com/idoenk/kaskus-quick-reply/blob/master/kaskus_quick_reply.user.js#L5347) _resolves_ the issue, but _I_ am not sure why it is encoded in the first place. Summon @Idx 

Relevant topic: [StackOverflow](https://stackoverflow.com/questions/16084935/a-html-space-is-showing-as-2520-instead-of-20)

🏃💨

**Comment by idoenk** [comment]
I dont recall why is that creature laying there --"
Anyway, <a href="https://github.com/idoenk/kaskus-quick-reply/commit/0ea4a1ce6675c0f78b02c23efe63837ca8902c52">patch applied</a> concern to that issue.
Thanks.
