### ISSUE TITLE
New Kaskus Emotes

### ISSUE THREAD

**Issue by coolkips** [idoenk/kaskus-quick-reply#4]
The update cover Kaskus Plus and Non Kaskus Plus emotes.

For Kaskus Plus emotes, there are some new emotes already up:
:nulisah http://s.kaskus.id/images/smilies/smilies_fb5ogntj5ay6.gif
:gagalpaham http://s.kaskus.id/images/smilies/smilies_fb5ogntmyt72.gif
:dor http://s.kaskus.id/images/smilies/smilies_fb5ogntptuty.gif
:ceyem http://s.kaskus.id/images/smilies/smilies_fb5ogktza4ll.gif
:sudahkuduga http://s.kaskus.id/images/smilies/smilies_fb5ognstk6ml.gif
:pencet http://s.kaskus.id/images/smilies/smilies_fb5ognt7s97w.gif
:gaasik http://s.kaskus.id/images/smilies/smilies_fb5ogntoc022.gif
:cih http://s.kaskus.id/images/smilies/smilies_fb5ogntt5wfk.gif

More update for Non Kaskus Plus emotes: http://www.kaskus.co.id/misc/getsmilies/

Thanks.
-ck-

**Comment by idoenk** [comment]
I'll look into it as soon I have my free time, maybe on next couple days.
Thanks, om ;)

**Comment by idoenk** [comment]
Patched, 0e90ec88a7a8fcc8cc4f8b0f4f8929eebd14b87a
Thanks.
