### ISSUE TITLE
Edit button is moved to right top corner

### ISSUE THREAD

**Issue by zackad** [idoenk/kaskus-quick-reply#6]
![Edit button moved to right top corner of post](https://i.imgur.com/2iZxBmx.png)

**Comment by idoenk** [comment]
Patched: [0e4242f](https://github.com/idoenk/kaskus-quick-reply/commit/0e4242ffed27304d09b09552971682b397515d3b)
Synced to [GF](https://greasyfork.org/en/scripts/96-kaskus-quick-reply-evo) v5.4.0.2

thx yoo.
