### ISSUE TITLE
Quick Quote break quoted post.

### ISSUE THREAD

**Issue by zackad** [idoenk/kaskus-quick-reply#8]
kaskus mengubah dom dari quote/quoted post. alhasil fitur quick quote tidak bekerja sebagaimana mestinya, fetch quote gak ada masalah.

contoh broken quoted post.
![2018-02-13_183454](https://user-images.githubusercontent.com/10742906/36147921-b2508e8c-10ec-11e8-9363-daf37aab900f.png)

---

## List of fixed parse with quick quote :
- [ ] Single quoted
- [ ] Several quoted
- [ ] Ordinary quote
- [ ] Code block
- [ ] HTML block
- [ ] PHP block
- [x] Single spoiler
- [x] Several spoiler
- [x] Kaskus emoticon
- [ ] Youtube embed
- [ ] Soundcloud embed

**Comment by idoenk** [comment]
Quick-quote should test and need adjustment on several cases:

* Post with (one/several) quoted post;
* Post with (one/several) spoiler;
* Post with audio/video embed. Eg. Youtube, soundcloud, ;
* Post with kaskus-emotes;
* 
*

**Comment by zackad** [comment]
blok kode php di kaskus juga lagi error. sepertinya bug gara-gara bentrok smilie code.

## Original code

```diff
<?php
if (PHP_SAPI == 'cli-server') {
    // To help the built-in PHP dev server, check if the request was actually for
    // something which should probably be served as a static file
    $url  = parse_url($_SERVER['REQUEST_URI']);
    $file = __DIR__ . $url['path'];
-    if (is_file($file)) {
+    if (is_file&#40;$file&#41<img src="https://s.kaskus.id/images/smilies/sumbangan/13.gif" data-sceditor-emoticon=";)"" border="0" alt="emoticon-Wink" title="Wink"/> {
        return false;
    }
}
```

**Comment by idoenk** [comment]
Biasa nih klo ada perubahan structure kudu re-adjust code. Blm klo emng msh ada bug dr sisi kaskus nya nge parse/render element ato atribut.
Hehe..

Later ane lanjut patch ya om.. 🙏

**Comment by zackad** [comment]
update ntar aja dah, soalnya kaskus juga blom stabil sistemnya. pasti bakal banyak perubahan sana-sini.
ane bikin list-nya biar ntar ng-ceknya lebih gampang.

anyway thanks buat script-nya.
